# Generated by Django 5.2.8 on 2025-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('object_type', models.CharField(max_length=10)),
                ('justwatch_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('justwatch_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Watchlist Title',
                'ordering': ['title'],
            },
        ),
    ]
